package io.github.sroca3.diplomacy.maps;

import io.github.sroca3.diplomacy.Country;
import io.github.sroca3.diplomacy.Location;
import io.github.sroca3.diplomacy.MapVariant;
import io.github.sroca3.diplomacy.UnitType;

import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.SortedSet;
import java.util.TreeSet;

public class SouthAmericanSupremacyMapVariant implements MapVariant {
    private static final Map<Location, Set<Location>> graph = new HashMap<>();
    private static final Map<Location, Set<Location>> fleetGraph = new HashMap<>();
    private static final SouthAmericanSupremacyMapVariant INSTANCE = new SouthAmericanSupremacyMapVariant();

    private SouthAmericanSupremacyMapVariant() {
        Arrays.stream(SouthAmericanSupremacyLocation.values()).forEach(l -> addEdge(graph, l, l));
        Arrays.stream(SouthAmericanSupremacyLocation.values()).forEach(l -> addEdge(fleetGraph, l, l));

        addEdge(graph, SouthAmericanSupremacyLocation.AMAZONAS, SouthAmericanSupremacyLocation.POPAYAN);
        addEdge(graph, SouthAmericanSupremacyLocation.AMAZONAS, SouthAmericanSupremacyLocation.RIO_BRANCO);
        addEdge(graph, SouthAmericanSupremacyLocation.AMAZONAS, SouthAmericanSupremacyLocation.IQUITOS);
        addEdge(graph, SouthAmericanSupremacyLocation.AMAZONAS, SouthAmericanSupremacyLocation.MANAUS);
        addEdge(graph, SouthAmericanSupremacyLocation.AMAZONAS, SouthAmericanSupremacyLocation.AQUIRIS);
        addEdge(graph, SouthAmericanSupremacyLocation.AMAZONAS, SouthAmericanSupremacyLocation.LLANOS);
        addEdge(graph, SouthAmericanSupremacyLocation.AMAZONAS, SouthAmericanSupremacyLocation.ORINOCO);
        addEdge(graph, SouthAmericanSupremacyLocation.AMAZONAS, SouthAmericanSupremacyLocation.MATO_GROSSO);
        addEdge(graph, SouthAmericanSupremacyLocation.PUNTA_ARENAS, SouthAmericanSupremacyLocation.ARAUNCANIAN);
        addEdge(graph, SouthAmericanSupremacyLocation.CORDOBA, SouthAmericanSupremacyLocation.ROSARIO);
        addEdge(graph, SouthAmericanSupremacyLocation.CORDOBA, SouthAmericanSupremacyLocation.SAN_MIGUEL_DE_TUCUMAN);
        addEdge(graph, SouthAmericanSupremacyLocation.CORDOBA, SouthAmericanSupremacyLocation.MENDOZA);
        addEdge(graph, SouthAmericanSupremacyLocation.COPIAGO, SouthAmericanSupremacyLocation.VALPARAISO);
        addEdge(graph, SouthAmericanSupremacyLocation.COPIAGO, SouthAmericanSupremacyLocation.ANTOFAGASTA);
        addEdge(graph, SouthAmericanSupremacyLocation.CORRIENTES, SouthAmericanSupremacyLocation.ASUNCION);
        addEdge(graph, SouthAmericanSupremacyLocation.CORRIENTES, SouthAmericanSupremacyLocation.FORMOSA);
        addEdge(graph, SouthAmericanSupremacyLocation.CORRIENTES, SouthAmericanSupremacyLocation.MISIONES);
        addEdge(graph, SouthAmericanSupremacyLocation.CORRIENTES, SouthAmericanSupremacyLocation.SAN_MIGUEL_DE_TUCUMAN);
        addEdge(graph, SouthAmericanSupremacyLocation.CORRIENTES, SouthAmericanSupremacyLocation.SANTA_FE);
        addEdge(graph, SouthAmericanSupremacyLocation.CUSCO, SouthAmericanSupremacyLocation.LA_PAZ);
        addEdge(graph, SouthAmericanSupremacyLocation.CUSCO, SouthAmericanSupremacyLocation.RIBERALTA);
        addEdge(graph, SouthAmericanSupremacyLocation.CUSCO, SouthAmericanSupremacyLocation.IQUITOS);
        addEdge(graph, SouthAmericanSupremacyLocation.CUSCO, SouthAmericanSupremacyLocation.LIMA);
        addEdge(graph, SouthAmericanSupremacyLocation.CUSCO, SouthAmericanSupremacyLocation.AQUIRIS);
        addEdge(graph, SouthAmericanSupremacyLocation.GUAPORE, SouthAmericanSupremacyLocation.RIBERALTA);
        addEdge(graph, SouthAmericanSupremacyLocation.GUAPORE, SouthAmericanSupremacyLocation.SANTA_CRUZ);
        addEdge(graph, SouthAmericanSupremacyLocation.GUAPORE, SouthAmericanSupremacyLocation.AQUIRIS);
        addEdge(graph, SouthAmericanSupremacyLocation.GUAPORE, SouthAmericanSupremacyLocation.MATO_GROSSO);
        addEdge(graph, SouthAmericanSupremacyLocation.PERNAMBUCO, SouthAmericanSupremacyLocation.SALVADOR);
        addEdge(graph, SouthAmericanSupremacyLocation.PERNAMBUCO, SouthAmericanSupremacyLocation.MARANHAO);
        addEdge(graph, SouthAmericanSupremacyLocation.PERNAMBUCO, SouthAmericanSupremacyLocation.GOIAS);
        addEdge(graph, SouthAmericanSupremacyLocation.PARANA, SouthAmericanSupremacyLocation.ASUNCION);
        addEdge(graph, SouthAmericanSupremacyLocation.PARANA, SouthAmericanSupremacyLocation.CONCEPCION);
        addEdge(graph, SouthAmericanSupremacyLocation.PARANA, SouthAmericanSupremacyLocation.MISIONES);
        addEdge(graph, SouthAmericanSupremacyLocation.PARANA, SouthAmericanSupremacyLocation.RIO_GRANDE_DO_SUL);
        addEdge(graph, SouthAmericanSupremacyLocation.PARANA, SouthAmericanSupremacyLocation.PANTANAL);
        addEdge(graph, SouthAmericanSupremacyLocation.RIO_DE_JANEIRO, SouthAmericanSupremacyLocation.SALVADOR);
        addEdge(graph, SouthAmericanSupremacyLocation.RIO_DE_JANEIRO, SouthAmericanSupremacyLocation.MINAS_GERAIS);
        addEdge(graph, SouthAmericanSupremacyLocation.RIO_DE_JANEIRO, SouthAmericanSupremacyLocation.SAO_PAULO);
        addEdge(graph, SouthAmericanSupremacyLocation.RIO_GRANDE_DO_SUL, SouthAmericanSupremacyLocation.PARANA);
        addEdge(graph, SouthAmericanSupremacyLocation.RIO_GRANDE_DO_SUL, SouthAmericanSupremacyLocation.SAO_PAULO);
        addEdge(graph, SouthAmericanSupremacyLocation.RIO_GRANDE_DO_SUL, SouthAmericanSupremacyLocation.MISIONES);
        addEdge(graph, SouthAmericanSupremacyLocation.RIO_GRANDE_DO_SUL, SouthAmericanSupremacyLocation.MONTEVIDEO);
        addEdge(graph, SouthAmericanSupremacyLocation.SANTA_CRUZ, SouthAmericanSupremacyLocation.LA_PAZ);
        addEdge(graph, SouthAmericanSupremacyLocation.SANTA_CRUZ, SouthAmericanSupremacyLocation.RIBERALTA);
        addEdge(graph, SouthAmericanSupremacyLocation.SANTA_CRUZ, SouthAmericanSupremacyLocation.GUAPORE);
        addEdge(graph, SouthAmericanSupremacyLocation.SANTA_CRUZ, SouthAmericanSupremacyLocation.POTOSI);
        addEdge(graph, SouthAmericanSupremacyLocation.SANTA_CRUZ, SouthAmericanSupremacyLocation.CHACO);
        addEdge(graph, SouthAmericanSupremacyLocation.SANTA_CRUZ, SouthAmericanSupremacyLocation.PANTANAL);
        addEdge(graph, SouthAmericanSupremacyLocation.SANTA_CRUZ, SouthAmericanSupremacyLocation.MATO_GROSSO);
        addEdge(graph, SouthAmericanSupremacyLocation.ASUNCION, SouthAmericanSupremacyLocation.CONCEPCION);
        addEdge(graph, SouthAmericanSupremacyLocation.ASUNCION, SouthAmericanSupremacyLocation.FORMOSA);
        addEdge(graph, SouthAmericanSupremacyLocation.ASUNCION, SouthAmericanSupremacyLocation.CORRIENTES);
        addEdge(graph, SouthAmericanSupremacyLocation.ASUNCION, SouthAmericanSupremacyLocation.PARANA);
        addEdge(graph, SouthAmericanSupremacyLocation.ASUNCION, SouthAmericanSupremacyLocation.MISIONES);
        addEdge(graph, SouthAmericanSupremacyLocation.QUITO, SouthAmericanSupremacyLocation.CALI);
        addEdge(graph, SouthAmericanSupremacyLocation.QUITO, SouthAmericanSupremacyLocation.GUAYAQUIL);
        addEdge(graph, SouthAmericanSupremacyLocation.SALVADOR, SouthAmericanSupremacyLocation.MINAS_GERAIS);
        addEdge(graph, SouthAmericanSupremacyLocation.SALVADOR, SouthAmericanSupremacyLocation.GOIAS);
        addEdge(graph, SouthAmericanSupremacyLocation.SALVADOR, SouthAmericanSupremacyLocation.PERNAMBUCO);
        addEdge(graph, SouthAmericanSupremacyLocation.SALVADOR, SouthAmericanSupremacyLocation.RIO_DE_JANEIRO);
        addEdge(graph, SouthAmericanSupremacyLocation.POTOSI, SouthAmericanSupremacyLocation.LA_PAZ);
        addEdge(graph, SouthAmericanSupremacyLocation.POTOSI, SouthAmericanSupremacyLocation.SALTA);
        addEdge(graph, SouthAmericanSupremacyLocation.POTOSI, SouthAmericanSupremacyLocation.FORMOSA);
        addEdge(graph, SouthAmericanSupremacyLocation.POTOSI, SouthAmericanSupremacyLocation.CHACO);
        addEdge(graph, SouthAmericanSupremacyLocation.POTOSI, SouthAmericanSupremacyLocation.SANTA_CRUZ);
        addEdge(graph, SouthAmericanSupremacyLocation.POTOSI, SouthAmericanSupremacyLocation.ANTOFAGASTA);
        addEdge(graph, SouthAmericanSupremacyLocation.BAHIA_BLANCA, SouthAmericanSupremacyLocation.PATAGONIA);
        addEdge(graph, SouthAmericanSupremacyLocation.BAHIA_BLANCA, SouthAmericanSupremacyLocation.ROSARIO);
        addEdge(graph, SouthAmericanSupremacyLocation.BAHIA_BLANCA, SouthAmericanSupremacyLocation.MENDOZA);
        addEdge(graph, SouthAmericanSupremacyLocation.SANTA_MARTA, SouthAmericanSupremacyLocation.BOGOTA);
        addEdge(graph, SouthAmericanSupremacyLocation.SANTA_MARTA, SouthAmericanSupremacyLocation.MARACAIBO);
        addEdge(graph, SouthAmericanSupremacyLocation.SANTA_MARTA, SouthAmericanSupremacyLocation.LLANOS);
        addEdge(graph, SouthAmericanSupremacyLocation.SANTA_MARTA, SouthAmericanSupremacyLocation.CARTAGENA);
        addEdge(graph, SouthAmericanSupremacyLocation.ROSARIO, SouthAmericanSupremacyLocation.CORDOBA);
        addEdge(graph, SouthAmericanSupremacyLocation.ROSARIO, SouthAmericanSupremacyLocation.BAHIA_BLANCA);
        addEdge(graph, SouthAmericanSupremacyLocation.ROSARIO, SouthAmericanSupremacyLocation.SANTA_FE);
        addEdge(graph, SouthAmericanSupremacyLocation.ROSARIO, SouthAmericanSupremacyLocation.MENDOZA);
        addEdge(graph, SouthAmericanSupremacyLocation.ROSARIO, SouthAmericanSupremacyLocation.BUENOS_AIRES);
        addEdge(graph, SouthAmericanSupremacyLocation.TRUJILLO, SouthAmericanSupremacyLocation.IQUITOS);
        addEdge(graph, SouthAmericanSupremacyLocation.TRUJILLO, SouthAmericanSupremacyLocation.LIMA);
        addEdge(graph, SouthAmericanSupremacyLocation.TRUJILLO, SouthAmericanSupremacyLocation.PIURA);
        addEdge(graph, SouthAmericanSupremacyLocation.MATO_GROSSO, SouthAmericanSupremacyLocation.PARA);
        addEdge(graph, SouthAmericanSupremacyLocation.MATO_GROSSO, SouthAmericanSupremacyLocation.AMAZONAS);
        addEdge(graph, SouthAmericanSupremacyLocation.MATO_GROSSO, SouthAmericanSupremacyLocation.MARANHAO);
        addEdge(graph, SouthAmericanSupremacyLocation.MATO_GROSSO, SouthAmericanSupremacyLocation.GUAPORE);
        addEdge(graph, SouthAmericanSupremacyLocation.MATO_GROSSO, SouthAmericanSupremacyLocation.GOIAS);
        addEdge(graph, SouthAmericanSupremacyLocation.MATO_GROSSO, SouthAmericanSupremacyLocation.MANAUS);
        addEdge(graph, SouthAmericanSupremacyLocation.MATO_GROSSO, SouthAmericanSupremacyLocation.SANTA_CRUZ);
        addEdge(graph, SouthAmericanSupremacyLocation.MATO_GROSSO, SouthAmericanSupremacyLocation.AQUIRIS);
        addEdge(graph, SouthAmericanSupremacyLocation.MATO_GROSSO, SouthAmericanSupremacyLocation.PANTANAL);
        addEdge(graph, SouthAmericanSupremacyLocation.PANAMA, SouthAmericanSupremacyLocation.VERAGUA);
        addEdge(graph, SouthAmericanSupremacyLocation.PANAMA, SouthAmericanSupremacyLocation.MEDELLIN);
        addEdge(graph, SouthAmericanSupremacyLocation.PANAMA, SouthAmericanSupremacyLocation.CARTAGENA);
        addEdge(graph, SouthAmericanSupremacyLocation.SANTIAGO, SouthAmericanSupremacyLocation.VALPARAISO);
        addEdge(graph, SouthAmericanSupremacyLocation.SANTIAGO, SouthAmericanSupremacyLocation.ARAUNCANIAN);
        addEdge(graph, SouthAmericanSupremacyLocation.SANTIAGO, SouthAmericanSupremacyLocation.MENDOZA);
        addEdge(graph, SouthAmericanSupremacyLocation.ANGOSTURA, SouthAmericanSupremacyLocation.CUMANA);
        addEdge(graph, SouthAmericanSupremacyLocation.ANGOSTURA, SouthAmericanSupremacyLocation.CARACAS);
        addEdge(graph, SouthAmericanSupremacyLocation.ANGOSTURA, SouthAmericanSupremacyLocation.RIO_BRANCO);
        addEdge(graph, SouthAmericanSupremacyLocation.SAO_PAULO, SouthAmericanSupremacyLocation.MINAS_GERAIS);
        addEdge(graph, SouthAmericanSupremacyLocation.SAO_PAULO, SouthAmericanSupremacyLocation.GOIAS);
        addEdge(graph, SouthAmericanSupremacyLocation.SAO_PAULO, SouthAmericanSupremacyLocation.RIO_GRANDE_DO_SUL);
        addEdge(graph, SouthAmericanSupremacyLocation.SAO_PAULO, SouthAmericanSupremacyLocation.RIO_DE_JANEIRO);
        addEdge(graph, SouthAmericanSupremacyLocation.SAO_PAULO, SouthAmericanSupremacyLocation.PANTANAL);
        addEdge(graph, SouthAmericanSupremacyLocation.AQUIRIS, SouthAmericanSupremacyLocation.AMAZONAS);
        addEdge(graph, SouthAmericanSupremacyLocation.AQUIRIS, SouthAmericanSupremacyLocation.RIBERALTA);
        addEdge(graph, SouthAmericanSupremacyLocation.AQUIRIS, SouthAmericanSupremacyLocation.IQUITOS);
        addEdge(graph, SouthAmericanSupremacyLocation.AQUIRIS, SouthAmericanSupremacyLocation.CUSCO);
        addEdge(graph, SouthAmericanSupremacyLocation.AQUIRIS, SouthAmericanSupremacyLocation.GUAPORE);
        addEdge(graph, SouthAmericanSupremacyLocation.AQUIRIS, SouthAmericanSupremacyLocation.MATO_GROSSO);
        addEdge(graph, SouthAmericanSupremacyLocation.GUAYAQUIL, SouthAmericanSupremacyLocation.QUITO);
        addEdge(graph, SouthAmericanSupremacyLocation.GUAYAQUIL, SouthAmericanSupremacyLocation.CANELOS);
        addEdge(graph, SouthAmericanSupremacyLocation.GUAYAQUIL, SouthAmericanSupremacyLocation.PIURA);
        addEdge(graph, SouthAmericanSupremacyLocation.MONTEVIDEO, SouthAmericanSupremacyLocation.MISIONES);
        addEdge(graph, SouthAmericanSupremacyLocation.MONTEVIDEO, SouthAmericanSupremacyLocation.RIO_GRANDE_DO_SUL);
        addEdge(graph, SouthAmericanSupremacyLocation.MONTEVIDEO, SouthAmericanSupremacyLocation.SANTA_FE);
        addEdge(graph, SouthAmericanSupremacyLocation.MONTEVIDEO, SouthAmericanSupremacyLocation.BUENOS_AIRES);
        addEdge(graph, SouthAmericanSupremacyLocation.CARACAS, SouthAmericanSupremacyLocation.MARACAIBO);
        addEdge(graph, SouthAmericanSupremacyLocation.CARACAS, SouthAmericanSupremacyLocation.CUMANA);
        addEdge(graph, SouthAmericanSupremacyLocation.CARACAS, SouthAmericanSupremacyLocation.ANGOSTURA);
        addEdge(graph, SouthAmericanSupremacyLocation.CARACAS, SouthAmericanSupremacyLocation.BARINAS);
        addEdge(graph, SouthAmericanSupremacyLocation.LA_PAZ, SouthAmericanSupremacyLocation.RIBERALTA);
        addEdge(graph, SouthAmericanSupremacyLocation.LA_PAZ, SouthAmericanSupremacyLocation.CUSCO);
        addEdge(graph, SouthAmericanSupremacyLocation.LA_PAZ, SouthAmericanSupremacyLocation.POTOSI);
        addEdge(graph, SouthAmericanSupremacyLocation.LA_PAZ, SouthAmericanSupremacyLocation.SANTA_CRUZ);
        addEdge(graph, SouthAmericanSupremacyLocation.RIBERALTA, SouthAmericanSupremacyLocation.LA_PAZ);
        addEdge(graph, SouthAmericanSupremacyLocation.RIBERALTA, SouthAmericanSupremacyLocation.GUAPORE);
        addEdge(graph, SouthAmericanSupremacyLocation.RIBERALTA, SouthAmericanSupremacyLocation.CUSCO);
        addEdge(graph, SouthAmericanSupremacyLocation.RIBERALTA, SouthAmericanSupremacyLocation.SANTA_CRUZ);
        addEdge(graph, SouthAmericanSupremacyLocation.RIBERALTA, SouthAmericanSupremacyLocation.AQUIRIS);
        addEdge(graph, SouthAmericanSupremacyLocation.PATAGONIA, SouthAmericanSupremacyLocation.BAHIA_BLANCA);
        addEdge(graph, SouthAmericanSupremacyLocation.PATAGONIA, SouthAmericanSupremacyLocation.ARAUNCANIAN);
        addEdge(graph, SouthAmericanSupremacyLocation.CANELOS, SouthAmericanSupremacyLocation.POPAYAN);
        addEdge(graph, SouthAmericanSupremacyLocation.CANELOS, SouthAmericanSupremacyLocation.CALI);
        addEdge(graph, SouthAmericanSupremacyLocation.CANELOS, SouthAmericanSupremacyLocation.GUAYAQUIL);
        addEdge(graph, SouthAmericanSupremacyLocation.RIO_BRANCO, SouthAmericanSupremacyLocation.PARA);
        addEdge(graph, SouthAmericanSupremacyLocation.RIO_BRANCO, SouthAmericanSupremacyLocation.AMAZONAS);
        addEdge(graph, SouthAmericanSupremacyLocation.RIO_BRANCO, SouthAmericanSupremacyLocation.MANAUS);
        addEdge(graph, SouthAmericanSupremacyLocation.RIO_BRANCO, SouthAmericanSupremacyLocation.ANGOSTURA);
        addEdge(graph, SouthAmericanSupremacyLocation.FORMOSA, SouthAmericanSupremacyLocation.ASUNCION);
        addEdge(graph, SouthAmericanSupremacyLocation.FORMOSA, SouthAmericanSupremacyLocation.CONCEPCION);
        addEdge(graph, SouthAmericanSupremacyLocation.FORMOSA, SouthAmericanSupremacyLocation.SALTA);
        addEdge(graph, SouthAmericanSupremacyLocation.FORMOSA, SouthAmericanSupremacyLocation.POTOSI);
        addEdge(graph, SouthAmericanSupremacyLocation.FORMOSA, SouthAmericanSupremacyLocation.CORRIENTES);
        addEdge(graph, SouthAmericanSupremacyLocation.FORMOSA, SouthAmericanSupremacyLocation.SAN_MIGUEL_DE_TUCUMAN);
        addEdge(graph, SouthAmericanSupremacyLocation.MANAUS, SouthAmericanSupremacyLocation.PARA);
        addEdge(graph, SouthAmericanSupremacyLocation.MANAUS, SouthAmericanSupremacyLocation.AMAZONAS);
        addEdge(graph, SouthAmericanSupremacyLocation.MANAUS, SouthAmericanSupremacyLocation.RIO_BRANCO);
        addEdge(graph, SouthAmericanSupremacyLocation.MANAUS, SouthAmericanSupremacyLocation.MATO_GROSSO);
        addEdge(graph, SouthAmericanSupremacyLocation.SCOTIA_SEA, SouthAmericanSupremacyLocation.ISLAS_MALVINAS);
        addEdge(graph, SouthAmericanSupremacyLocation.ATACAMA, SouthAmericanSupremacyLocation.ARICA);
        addEdge(graph, SouthAmericanSupremacyLocation.ATACAMA, SouthAmericanSupremacyLocation.ANTOFAGASTA);
        addEdge(graph, SouthAmericanSupremacyLocation.PIURA, SouthAmericanSupremacyLocation.GUAYAQUIL);
        addEdge(graph, SouthAmericanSupremacyLocation.PIURA, SouthAmericanSupremacyLocation.TRUJILLO);
        addEdge(graph, SouthAmericanSupremacyLocation.MEDELLIN, SouthAmericanSupremacyLocation.BOGOTA);
        addEdge(graph, SouthAmericanSupremacyLocation.MEDELLIN, SouthAmericanSupremacyLocation.CALI);
        addEdge(graph, SouthAmericanSupremacyLocation.MEDELLIN, SouthAmericanSupremacyLocation.PANAMA);
        addEdge(graph, SouthAmericanSupremacyLocation.MEDELLIN, SouthAmericanSupremacyLocation.CARTAGENA);
        addEdge(graph, SouthAmericanSupremacyLocation.BOGOTA, SouthAmericanSupremacyLocation.POPAYAN);
        addEdge(graph, SouthAmericanSupremacyLocation.BOGOTA, SouthAmericanSupremacyLocation.CALI);
        addEdge(graph, SouthAmericanSupremacyLocation.BOGOTA, SouthAmericanSupremacyLocation.SANTA_MARTA);
        addEdge(graph, SouthAmericanSupremacyLocation.BOGOTA, SouthAmericanSupremacyLocation.LLANOS);
        addEdge(graph, SouthAmericanSupremacyLocation.BOGOTA, SouthAmericanSupremacyLocation.CARTAGENA);
        addEdge(graph, SouthAmericanSupremacyLocation.BOGOTA, SouthAmericanSupremacyLocation.MEDELLIN);
        addEdge(graph, SouthAmericanSupremacyLocation.AREQUIPA, SouthAmericanSupremacyLocation.ARICA);
        addEdge(graph, SouthAmericanSupremacyLocation.AREQUIPA, SouthAmericanSupremacyLocation.LIMA);
        addEdge(graph, SouthAmericanSupremacyLocation.CONCEPCION, SouthAmericanSupremacyLocation.ASUNCION);
        addEdge(graph, SouthAmericanSupremacyLocation.CONCEPCION, SouthAmericanSupremacyLocation.FORMOSA);
        addEdge(graph, SouthAmericanSupremacyLocation.CONCEPCION, SouthAmericanSupremacyLocation.CHACO);
        addEdge(graph, SouthAmericanSupremacyLocation.CONCEPCION, SouthAmericanSupremacyLocation.PARANA);
        addEdge(graph, SouthAmericanSupremacyLocation.CONCEPCION, SouthAmericanSupremacyLocation.PANTANAL);
        addEdge(graph, SouthAmericanSupremacyLocation.CALI, SouthAmericanSupremacyLocation.BOGOTA);
        addEdge(graph, SouthAmericanSupremacyLocation.CALI, SouthAmericanSupremacyLocation.QUITO);
        addEdge(graph, SouthAmericanSupremacyLocation.CALI, SouthAmericanSupremacyLocation.CANELOS);
        addEdge(graph, SouthAmericanSupremacyLocation.CALI, SouthAmericanSupremacyLocation.MEDELLIN);
        addEdge(graph, SouthAmericanSupremacyLocation.ARICA, SouthAmericanSupremacyLocation.AREQUIPA);
        addEdge(graph, SouthAmericanSupremacyLocation.ARICA, SouthAmericanSupremacyLocation.ATACAMA);
        addEdge(graph, SouthAmericanSupremacyLocation.MARANHAO, SouthAmericanSupremacyLocation.PARA);
        addEdge(graph, SouthAmericanSupremacyLocation.MARANHAO, SouthAmericanSupremacyLocation.GOIAS);
        addEdge(graph, SouthAmericanSupremacyLocation.MARANHAO, SouthAmericanSupremacyLocation.PERNAMBUCO);
        addEdge(graph, SouthAmericanSupremacyLocation.MARANHAO, SouthAmericanSupremacyLocation.MATO_GROSSO);
        addEdge(graph, SouthAmericanSupremacyLocation.VERAGUA, SouthAmericanSupremacyLocation.PANAMA);
        addEdge(graph, SouthAmericanSupremacyLocation.CHACO, SouthAmericanSupremacyLocation.CONCEPCION);
        addEdge(graph, SouthAmericanSupremacyLocation.CHACO, SouthAmericanSupremacyLocation.POTOSI);
        addEdge(graph, SouthAmericanSupremacyLocation.CHACO, SouthAmericanSupremacyLocation.SANTA_CRUZ);
        addEdge(graph, SouthAmericanSupremacyLocation.CHACO, SouthAmericanSupremacyLocation.PANTANAL);
        addEdge(graph, SouthAmericanSupremacyLocation.MISIONES, SouthAmericanSupremacyLocation.ASUNCION);
        addEdge(graph, SouthAmericanSupremacyLocation.MISIONES, SouthAmericanSupremacyLocation.CORRIENTES);
        addEdge(graph, SouthAmericanSupremacyLocation.MISIONES, SouthAmericanSupremacyLocation.PARANA);
        addEdge(graph, SouthAmericanSupremacyLocation.MISIONES, SouthAmericanSupremacyLocation.RIO_GRANDE_DO_SUL);
        addEdge(graph, SouthAmericanSupremacyLocation.MISIONES, SouthAmericanSupremacyLocation.SANTA_FE);
        addEdge(graph, SouthAmericanSupremacyLocation.MISIONES, SouthAmericanSupremacyLocation.MONTEVIDEO);
        addEdge(graph, SouthAmericanSupremacyLocation.PANTANAL, SouthAmericanSupremacyLocation.CONCEPCION);
        addEdge(graph, SouthAmericanSupremacyLocation.PANTANAL, SouthAmericanSupremacyLocation.CHACO);
        addEdge(graph, SouthAmericanSupremacyLocation.PANTANAL, SouthAmericanSupremacyLocation.PARANA);
        addEdge(graph, SouthAmericanSupremacyLocation.PANTANAL, SouthAmericanSupremacyLocation.SAO_PAULO);
        addEdge(graph, SouthAmericanSupremacyLocation.PANTANAL, SouthAmericanSupremacyLocation.SANTA_CRUZ);
        addEdge(graph, SouthAmericanSupremacyLocation.PANTANAL, SouthAmericanSupremacyLocation.MATO_GROSSO);
        addEdge(graph, SouthAmericanSupremacyLocation.ARAUNCANIAN, SouthAmericanSupremacyLocation.PUNTA_ARENAS);
        addEdge(graph, SouthAmericanSupremacyLocation.ARAUNCANIAN, SouthAmericanSupremacyLocation.SANTIAGO);
        addEdge(graph, SouthAmericanSupremacyLocation.ARAUNCANIAN, SouthAmericanSupremacyLocation.PATAGONIA);
        addEdge(graph, SouthAmericanSupremacyLocation.POPAYAN, SouthAmericanSupremacyLocation.BOGOTA);
        addEdge(graph, SouthAmericanSupremacyLocation.POPAYAN, SouthAmericanSupremacyLocation.AMAZONAS);
        addEdge(graph, SouthAmericanSupremacyLocation.POPAYAN, SouthAmericanSupremacyLocation.CANELOS);
        addEdge(graph, SouthAmericanSupremacyLocation.POPAYAN, SouthAmericanSupremacyLocation.IQUITOS);
        addEdge(graph, SouthAmericanSupremacyLocation.POPAYAN, SouthAmericanSupremacyLocation.LLANOS);
        addEdge(graph, SouthAmericanSupremacyLocation.POPAYAN, SouthAmericanSupremacyLocation.ORINOCO);
        addEdge(graph, SouthAmericanSupremacyLocation.IQUITOS, SouthAmericanSupremacyLocation.AMAZONAS);
        addEdge(graph, SouthAmericanSupremacyLocation.IQUITOS, SouthAmericanSupremacyLocation.POPAYAN);
        addEdge(graph, SouthAmericanSupremacyLocation.IQUITOS, SouthAmericanSupremacyLocation.CUSCO);
        addEdge(graph, SouthAmericanSupremacyLocation.IQUITOS, SouthAmericanSupremacyLocation.AQUIRIS);
        addEdge(graph, SouthAmericanSupremacyLocation.IQUITOS, SouthAmericanSupremacyLocation.TRUJILLO);
        addEdge(graph, SouthAmericanSupremacyLocation.MINAS_GERAIS, SouthAmericanSupremacyLocation.SALVADOR);
        addEdge(graph, SouthAmericanSupremacyLocation.MINAS_GERAIS, SouthAmericanSupremacyLocation.GOIAS);
        addEdge(graph, SouthAmericanSupremacyLocation.MINAS_GERAIS, SouthAmericanSupremacyLocation.SAO_PAULO);
        addEdge(graph, SouthAmericanSupremacyLocation.MINAS_GERAIS, SouthAmericanSupremacyLocation.RIO_DE_JANEIRO);
        addEdge(graph, SouthAmericanSupremacyLocation.GOIAS, SouthAmericanSupremacyLocation.SALVADOR);
        addEdge(graph, SouthAmericanSupremacyLocation.GOIAS, SouthAmericanSupremacyLocation.MINAS_GERAIS);
        addEdge(graph, SouthAmericanSupremacyLocation.GOIAS, SouthAmericanSupremacyLocation.MARANHAO);
        addEdge(graph, SouthAmericanSupremacyLocation.GOIAS, SouthAmericanSupremacyLocation.PERNAMBUCO);
        addEdge(graph, SouthAmericanSupremacyLocation.GOIAS, SouthAmericanSupremacyLocation.SAO_PAULO);
        addEdge(graph, SouthAmericanSupremacyLocation.GOIAS, SouthAmericanSupremacyLocation.MATO_GROSSO);
        addEdge(graph, SouthAmericanSupremacyLocation.ISLAS_MALVINAS, SouthAmericanSupremacyLocation.SCOTIA_SEA);
        addEdge(graph, SouthAmericanSupremacyLocation.LLANOS, SouthAmericanSupremacyLocation.BOGOTA);
        addEdge(graph, SouthAmericanSupremacyLocation.LLANOS, SouthAmericanSupremacyLocation.MARACAIBO);
        addEdge(graph, SouthAmericanSupremacyLocation.LLANOS, SouthAmericanSupremacyLocation.AMAZONAS);
        addEdge(graph, SouthAmericanSupremacyLocation.LLANOS, SouthAmericanSupremacyLocation.POPAYAN);
        addEdge(graph, SouthAmericanSupremacyLocation.LLANOS, SouthAmericanSupremacyLocation.SANTA_MARTA);
        addEdge(graph, SouthAmericanSupremacyLocation.LLANOS, SouthAmericanSupremacyLocation.BARINAS);
        addEdge(graph, SouthAmericanSupremacyLocation.LLANOS, SouthAmericanSupremacyLocation.ORINOCO);
        addEdge(graph, SouthAmericanSupremacyLocation.ANTOFAGASTA, SouthAmericanSupremacyLocation.COPIAGO);
        addEdge(graph, SouthAmericanSupremacyLocation.ANTOFAGASTA, SouthAmericanSupremacyLocation.POTOSI);
        addEdge(graph, SouthAmericanSupremacyLocation.ANTOFAGASTA, SouthAmericanSupremacyLocation.ATACAMA);
        addEdge(graph, SouthAmericanSupremacyLocation.MENDOZA, SouthAmericanSupremacyLocation.CORDOBA);
        addEdge(graph, SouthAmericanSupremacyLocation.MENDOZA, SouthAmericanSupremacyLocation.SANTIAGO);
        addEdge(graph, SouthAmericanSupremacyLocation.MENDOZA, SouthAmericanSupremacyLocation.BAHIA_BLANCA);
        addEdge(graph, SouthAmericanSupremacyLocation.MENDOZA, SouthAmericanSupremacyLocation.ROSARIO);
        addEdge(graph, SouthAmericanSupremacyLocation.CUMANA, SouthAmericanSupremacyLocation.CARACAS);
        addEdge(graph, SouthAmericanSupremacyLocation.CUMANA, SouthAmericanSupremacyLocation.ANGOSTURA);
        addEdge(graph, SouthAmericanSupremacyLocation.PARA, SouthAmericanSupremacyLocation.RIO_BRANCO);
        addEdge(graph, SouthAmericanSupremacyLocation.PARA, SouthAmericanSupremacyLocation.MARANHAO);
        addEdge(graph, SouthAmericanSupremacyLocation.PARA, SouthAmericanSupremacyLocation.MANAUS);
        addEdge(graph, SouthAmericanSupremacyLocation.PARA, SouthAmericanSupremacyLocation.MATO_GROSSO);
        addEdge(graph, SouthAmericanSupremacyLocation.SALTA, SouthAmericanSupremacyLocation.POTOSI);
        addEdge(graph, SouthAmericanSupremacyLocation.SALTA, SouthAmericanSupremacyLocation.FORMOSA);
        addEdge(graph, SouthAmericanSupremacyLocation.SALTA, SouthAmericanSupremacyLocation.SAN_MIGUEL_DE_TUCUMAN);
        addEdge(graph, SouthAmericanSupremacyLocation.SAN_MIGUEL_DE_TUCUMAN, SouthAmericanSupremacyLocation.SALTA);
        addEdge(graph, SouthAmericanSupremacyLocation.SAN_MIGUEL_DE_TUCUMAN, SouthAmericanSupremacyLocation.CORDOBA);
        addEdge(graph, SouthAmericanSupremacyLocation.SAN_MIGUEL_DE_TUCUMAN, SouthAmericanSupremacyLocation.FORMOSA);
        addEdge(graph, SouthAmericanSupremacyLocation.SAN_MIGUEL_DE_TUCUMAN, SouthAmericanSupremacyLocation.CORRIENTES);
        addEdge(graph, SouthAmericanSupremacyLocation.SAN_MIGUEL_DE_TUCUMAN, SouthAmericanSupremacyLocation.SANTA_FE);
        addEdge(graph, SouthAmericanSupremacyLocation.VALPARAISO, SouthAmericanSupremacyLocation.SANTIAGO);
        addEdge(graph, SouthAmericanSupremacyLocation.VALPARAISO, SouthAmericanSupremacyLocation.COPIAGO);
        addEdge(graph, SouthAmericanSupremacyLocation.ORINOCO, SouthAmericanSupremacyLocation.AMAZONAS);
        addEdge(graph, SouthAmericanSupremacyLocation.ORINOCO, SouthAmericanSupremacyLocation.POPAYAN);
        addEdge(graph, SouthAmericanSupremacyLocation.ORINOCO, SouthAmericanSupremacyLocation.BARINAS);
        addEdge(graph, SouthAmericanSupremacyLocation.ORINOCO, SouthAmericanSupremacyLocation.LLANOS);
        addEdge(graph, SouthAmericanSupremacyLocation.BUENOS_AIRES, SouthAmericanSupremacyLocation.ROSARIO);
        addEdge(graph, SouthAmericanSupremacyLocation.BUENOS_AIRES, SouthAmericanSupremacyLocation.SANTA_FE);
        addEdge(graph, SouthAmericanSupremacyLocation.BUENOS_AIRES, SouthAmericanSupremacyLocation.MONTEVIDEO);
        addEdge(graph, SouthAmericanSupremacyLocation.MARACAIBO, SouthAmericanSupremacyLocation.CARACAS);
        addEdge(graph, SouthAmericanSupremacyLocation.MARACAIBO, SouthAmericanSupremacyLocation.SANTA_MARTA);
        addEdge(graph, SouthAmericanSupremacyLocation.MARACAIBO, SouthAmericanSupremacyLocation.BARINAS);
        addEdge(graph, SouthAmericanSupremacyLocation.MARACAIBO, SouthAmericanSupremacyLocation.LLANOS);
        addEdge(graph, SouthAmericanSupremacyLocation.LIMA, SouthAmericanSupremacyLocation.AREQUIPA);
        addEdge(graph, SouthAmericanSupremacyLocation.LIMA, SouthAmericanSupremacyLocation.CUSCO);
        addEdge(graph, SouthAmericanSupremacyLocation.LIMA, SouthAmericanSupremacyLocation.TRUJILLO);
        addEdge(graph, SouthAmericanSupremacyLocation.BARINAS, SouthAmericanSupremacyLocation.MARACAIBO);
        addEdge(graph, SouthAmericanSupremacyLocation.BARINAS, SouthAmericanSupremacyLocation.CARACAS);
        addEdge(graph, SouthAmericanSupremacyLocation.BARINAS, SouthAmericanSupremacyLocation.LLANOS);
        addEdge(graph, SouthAmericanSupremacyLocation.BARINAS, SouthAmericanSupremacyLocation.ORINOCO);
        addEdge(graph, SouthAmericanSupremacyLocation.SANTA_FE, SouthAmericanSupremacyLocation.CORRIENTES);
        addEdge(graph, SouthAmericanSupremacyLocation.SANTA_FE, SouthAmericanSupremacyLocation.MISIONES);
        addEdge(graph, SouthAmericanSupremacyLocation.SANTA_FE, SouthAmericanSupremacyLocation.ROSARIO);
        addEdge(graph, SouthAmericanSupremacyLocation.SANTA_FE, SouthAmericanSupremacyLocation.SAN_MIGUEL_DE_TUCUMAN);
        addEdge(graph, SouthAmericanSupremacyLocation.SANTA_FE, SouthAmericanSupremacyLocation.MONTEVIDEO);
        addEdge(graph, SouthAmericanSupremacyLocation.SANTA_FE, SouthAmericanSupremacyLocation.BUENOS_AIRES);
        addEdge(graph, SouthAmericanSupremacyLocation.CARTAGENA, SouthAmericanSupremacyLocation.BOGOTA);
        addEdge(graph, SouthAmericanSupremacyLocation.CARTAGENA, SouthAmericanSupremacyLocation.SANTA_MARTA);
        addEdge(graph, SouthAmericanSupremacyLocation.CARTAGENA, SouthAmericanSupremacyLocation.PANAMA);
        addEdge(graph, SouthAmericanSupremacyLocation.CARTAGENA, SouthAmericanSupremacyLocation.MEDELLIN);

        addEdge(fleetGraph, SouthAmericanSupremacyLocation.SOUTH_ATLANTIC_OCEAN, SouthAmericanSupremacyLocation.GOLFO_DE_SAN_JORGE);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.SOUTH_ATLANTIC_OCEAN, SouthAmericanSupremacyLocation.BAHIA_DE_PARANAGUA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.SOUTH_ATLANTIC_OCEAN, SouthAmericanSupremacyLocation.RIO_DE_LA_PLATA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.ISLAS_JUAN_FERNANDEZ, SouthAmericanSupremacyLocation.DRAKE_PASSAGE);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.ISLAS_JUAN_FERNANDEZ, SouthAmericanSupremacyLocation.GOLFO_DE_GUAFO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.ATACAMA, SouthAmericanSupremacyLocation.ANTOFAGASTA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.ATACAMA, SouthAmericanSupremacyLocation.ARICA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.ATACAMA, SouthAmericanSupremacyLocation.BAHIA_DE_ARICA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.ARAUNCANIAN, SouthAmericanSupremacyLocation.SANTIAGO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.ARAUNCANIAN, SouthAmericanSupremacyLocation.PUNTA_ARENAS);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.ARAUNCANIAN, SouthAmericanSupremacyLocation.PATAGONIA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.ARAUNCANIAN, SouthAmericanSupremacyLocation.DRAKE_PASSAGE);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.BAHIA_DE_SAO_SEBASTAO, SouthAmericanSupremacyLocation.BAHIA_DE_TODOS_OS_SANTOS);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.BAHIA_DE_SAO_SEBASTAO, SouthAmericanSupremacyLocation.SAO_PAULO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.BAHIA_DE_SAO_SEBASTAO, SouthAmericanSupremacyLocation.BAHIA_DE_PARANAGUA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.BAHIA_DE_SAO_SEBASTAO, SouthAmericanSupremacyLocation.RIO_DE_JANEIRO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.GOLFO_DE_PANAMA, SouthAmericanSupremacyLocation.BAHIA_SECHURA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.GOLFO_DE_PANAMA, SouthAmericanSupremacyLocation.ISLAS_GALAPAGOS);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.GOLFO_DE_PANAMA, SouthAmericanSupremacyLocation.CALI);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.GOLFO_DE_PANAMA, SouthAmericanSupremacyLocation.MEDELLIN);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.BAHIA_DE_TODOS_OS_SANTOS, SouthAmericanSupremacyLocation.SALVADOR);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.BAHIA_DE_TODOS_OS_SANTOS, SouthAmericanSupremacyLocation.BAHIA_DE_SAO_SEBASTAO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.BAHIA_DE_TODOS_OS_SANTOS, SouthAmericanSupremacyLocation.BAHIA_SAO_MARCOS);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.BAHIA_DE_TODOS_OS_SANTOS, SouthAmericanSupremacyLocation.BAHIA_DE_PARANAGUA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.BAHIA_DE_TODOS_OS_SANTOS, SouthAmericanSupremacyLocation.RIO_DE_JANEIRO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.MATO_GROSSO, SouthAmericanSupremacyLocation.MANAUS);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.MATO_GROSSO, SouthAmericanSupremacyLocation.AMAZONAS);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.MATO_GROSSO, SouthAmericanSupremacyLocation.PARA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.MATO_GROSSO, SouthAmericanSupremacyLocation.MARANHAO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.GOLFO_DE_PARIA, SouthAmericanSupremacyLocation.CARACAS);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.GOLFO_DE_PARIA, SouthAmericanSupremacyLocation.CUMANA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.GOLFO_DE_PARIA, SouthAmericanSupremacyLocation.ATLANTIC_OCEAN);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.GOLFO_DE_PARIA, SouthAmericanSupremacyLocation.BOCA_DE_NAVIOS);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.GOLFO_DE_PARIA, SouthAmericanSupremacyLocation.GOLFO_DE_DARIEN);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.CARTAGENA, SouthAmericanSupremacyLocation.SANTA_MARTA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.CARTAGENA, SouthAmericanSupremacyLocation.GOLFO_DE_DARIEN);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.CARTAGENA, SouthAmericanSupremacyLocation.MEDELLIN);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.BUENOS_AIRES, SouthAmericanSupremacyLocation.MONTEVIDEO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.BUENOS_AIRES, SouthAmericanSupremacyLocation.RIO_DE_LA_PLATA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.BOCA_DE_NAVIOS, SouthAmericanSupremacyLocation.CUMANA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.BOCA_DE_NAVIOS, SouthAmericanSupremacyLocation.GOLFO_DE_PARIA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.BOCA_DE_NAVIOS, SouthAmericanSupremacyLocation.ATLANTIC_OCEAN);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.BOCA_DE_NAVIOS, SouthAmericanSupremacyLocation.ANGOSTURA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.BOCA_DE_NAVIOS, SouthAmericanSupremacyLocation.PARA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.BOCA_DE_NAVIOS, SouthAmericanSupremacyLocation.MARANHAO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.MONTEVIDEO, SouthAmericanSupremacyLocation.RIO_GRANDE_DO_SUL);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.MONTEVIDEO, SouthAmericanSupremacyLocation.RIO_DE_LA_PLATA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.MONTEVIDEO, SouthAmericanSupremacyLocation.MISIONES);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.MONTEVIDEO, SouthAmericanSupremacyLocation.BUENOS_AIRES);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.MANAUS, SouthAmericanSupremacyLocation.MATO_GROSSO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.MANAUS, SouthAmericanSupremacyLocation.AMAZONAS);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.MANAUS, SouthAmericanSupremacyLocation.PARA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.MARACAIBO, SouthAmericanSupremacyLocation.SANTA_MARTA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.MARACAIBO, SouthAmericanSupremacyLocation.CARACAS);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.MARACAIBO, SouthAmericanSupremacyLocation.GOLFO_DE_DARIEN);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.TRUJILLO, SouthAmericanSupremacyLocation.NAZCA_SEA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.TRUJILLO, SouthAmericanSupremacyLocation.LIMA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.CUMANA, SouthAmericanSupremacyLocation.CARACAS);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.CUMANA, SouthAmericanSupremacyLocation.GOLFO_DE_PARIA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.CUMANA, SouthAmericanSupremacyLocation.ANGOSTURA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.CUMANA, SouthAmericanSupremacyLocation.BOCA_DE_NAVIOS);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.BAHIA_SECHURA, SouthAmericanSupremacyLocation.NAZCA_SEA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.BAHIA_SECHURA, SouthAmericanSupremacyLocation.ISLAS_GALAPAGOS);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.BAHIA_SECHURA, SouthAmericanSupremacyLocation.CALI);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.BAHIA_SECHURA, SouthAmericanSupremacyLocation.GOLFO_DE_PANAMA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.ANGOSTURA, SouthAmericanSupremacyLocation.CARACAS);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.ANGOSTURA, SouthAmericanSupremacyLocation.CUMANA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.ANGOSTURA, SouthAmericanSupremacyLocation.BOCA_DE_NAVIOS);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.ATLANTIC_OCEAN, SouthAmericanSupremacyLocation.GOLFO_DE_PARIA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.ATLANTIC_OCEAN, SouthAmericanSupremacyLocation.BAHIA_SAO_MARCOS);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.ATLANTIC_OCEAN, SouthAmericanSupremacyLocation.BOCA_DE_NAVIOS);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.LIMA, SouthAmericanSupremacyLocation.TRUJILLO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.LIMA, SouthAmericanSupremacyLocation.NAZCA_SEA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.LIMA, SouthAmericanSupremacyLocation.AREQUIPA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.LIMA, SouthAmericanSupremacyLocation.BAHIA_DE_ARICA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.DRAKE_PASSAGE, SouthAmericanSupremacyLocation.ISLAS_JUAN_FERNANDEZ);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.DRAKE_PASSAGE, SouthAmericanSupremacyLocation.SANTIAGO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.DRAKE_PASSAGE, SouthAmericanSupremacyLocation.ARAUNCANIAN);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.DRAKE_PASSAGE, SouthAmericanSupremacyLocation.GOLFO_DE_GUAFO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.BAHIA_DE_ARICA, SouthAmericanSupremacyLocation.ANTOFAGASTA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.BAHIA_DE_ARICA, SouthAmericanSupremacyLocation.NAZCA_SEA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.BAHIA_DE_ARICA, SouthAmericanSupremacyLocation.ARICA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.BAHIA_DE_ARICA, SouthAmericanSupremacyLocation.AREQUIPA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.BAHIA_DE_ARICA, SouthAmericanSupremacyLocation.ATACAMA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.BAHIA_DE_ARICA, SouthAmericanSupremacyLocation.LIMA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.BAHIA_DE_ARICA, SouthAmericanSupremacyLocation.GOLFO_DE_GUAFO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.GUAYAQUIL, SouthAmericanSupremacyLocation.QUITO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.MISIONES, SouthAmericanSupremacyLocation.MONTEVIDEO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.MISIONES, SouthAmericanSupremacyLocation.ASUNCION);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.MISIONES, SouthAmericanSupremacyLocation.PARANA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.MISIONES, SouthAmericanSupremacyLocation.RIO_GRANDE_DO_SUL);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.MISIONES, SouthAmericanSupremacyLocation.CORRIENTES);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.SANTA_MARTA, SouthAmericanSupremacyLocation.MARACAIBO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.SANTA_MARTA, SouthAmericanSupremacyLocation.CARTAGENA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.SANTA_MARTA, SouthAmericanSupremacyLocation.GOLFO_DE_DARIEN);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.ANTOFAGASTA, SouthAmericanSupremacyLocation.COPIAGO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.ANTOFAGASTA, SouthAmericanSupremacyLocation.ATACAMA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.ANTOFAGASTA, SouthAmericanSupremacyLocation.BAHIA_DE_ARICA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.ANTOFAGASTA, SouthAmericanSupremacyLocation.GOLFO_DE_GUAFO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.VALPARAISO, SouthAmericanSupremacyLocation.COPIAGO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.VALPARAISO, SouthAmericanSupremacyLocation.SANTIAGO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.VALPARAISO, SouthAmericanSupremacyLocation.GOLFO_DE_GUAFO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.CARACAS, SouthAmericanSupremacyLocation.MARACAIBO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.CARACAS, SouthAmericanSupremacyLocation.CUMANA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.CARACAS, SouthAmericanSupremacyLocation.GOLFO_DE_PARIA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.CARACAS, SouthAmericanSupremacyLocation.ANGOSTURA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.CARACAS, SouthAmericanSupremacyLocation.GOLFO_DE_DARIEN);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.SAO_PAULO, SouthAmericanSupremacyLocation.BAHIA_DE_SAO_SEBASTAO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.SAO_PAULO, SouthAmericanSupremacyLocation.RIO_GRANDE_DO_SUL);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.SAO_PAULO, SouthAmericanSupremacyLocation.RIO_DE_JANEIRO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.ISLAS_GALAPAGOS, SouthAmericanSupremacyLocation.NAZCA_SEA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.ISLAS_GALAPAGOS, SouthAmericanSupremacyLocation.BAHIA_SECHURA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.ISLAS_GALAPAGOS, SouthAmericanSupremacyLocation.GOLFO_DE_PANAMA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.AREQUIPA, SouthAmericanSupremacyLocation.ARICA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.AREQUIPA, SouthAmericanSupremacyLocation.LIMA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.AREQUIPA, SouthAmericanSupremacyLocation.BAHIA_DE_ARICA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.BAHIA_DE_PARANAGUA, SouthAmericanSupremacyLocation.BAHIA_DE_TODOS_OS_SANTOS);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.BAHIA_DE_PARANAGUA, SouthAmericanSupremacyLocation.SOUTH_ATLANTIC_OCEAN);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.BAHIA_DE_PARANAGUA, SouthAmericanSupremacyLocation.BAHIA_DE_SAO_SEBASTAO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.BAHIA_DE_PARANAGUA, SouthAmericanSupremacyLocation.RIO_DE_LA_PLATA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.QUITO, SouthAmericanSupremacyLocation.CALI);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.QUITO, SouthAmericanSupremacyLocation.GUAYAQUIL);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.MARANHAO, SouthAmericanSupremacyLocation.MATO_GROSSO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.MARANHAO, SouthAmericanSupremacyLocation.BAHIA_SAO_MARCOS);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.MARANHAO, SouthAmericanSupremacyLocation.BOCA_DE_NAVIOS);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.MARANHAO, SouthAmericanSupremacyLocation.PARA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.PARANA, SouthAmericanSupremacyLocation.ASUNCION);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.PARANA, SouthAmericanSupremacyLocation.RIO_GRANDE_DO_SUL);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.PARANA, SouthAmericanSupremacyLocation.MISIONES);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.PARANA, SouthAmericanSupremacyLocation.CONCEPCION);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.RIO_DE_LA_PLATA, SouthAmericanSupremacyLocation.SOUTH_ATLANTIC_OCEAN);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.RIO_DE_LA_PLATA, SouthAmericanSupremacyLocation.MONTEVIDEO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.RIO_DE_LA_PLATA, SouthAmericanSupremacyLocation.BAHIA_BLANCA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.RIO_DE_LA_PLATA, SouthAmericanSupremacyLocation.GOLFO_DE_SAN_JORGE);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.RIO_DE_LA_PLATA, SouthAmericanSupremacyLocation.BAHIA_DE_PARANAGUA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.RIO_DE_LA_PLATA, SouthAmericanSupremacyLocation.RIO_GRANDE_DO_SUL);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.RIO_DE_LA_PLATA, SouthAmericanSupremacyLocation.BUENOS_AIRES);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.RIO_DE_JANEIRO, SouthAmericanSupremacyLocation.BAHIA_DE_TODOS_OS_SANTOS);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.RIO_DE_JANEIRO, SouthAmericanSupremacyLocation.SAO_PAULO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.RIO_DE_JANEIRO, SouthAmericanSupremacyLocation.SALVADOR);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.RIO_DE_JANEIRO, SouthAmericanSupremacyLocation.BAHIA_DE_SAO_SEBASTAO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.ISLAS_MALVINAS, SouthAmericanSupremacyLocation.GOLFO_DE_SAN_JORGE);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.BAHIA_BLANCA, SouthAmericanSupremacyLocation.PATAGONIA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.BAHIA_BLANCA, SouthAmericanSupremacyLocation.GOLFO_DE_SAN_JORGE);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.BAHIA_BLANCA, SouthAmericanSupremacyLocation.RIO_DE_LA_PLATA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.NAZCA_SEA, SouthAmericanSupremacyLocation.TRUJILLO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.NAZCA_SEA, SouthAmericanSupremacyLocation.BAHIA_SECHURA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.NAZCA_SEA, SouthAmericanSupremacyLocation.ISLAS_GALAPAGOS);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.NAZCA_SEA, SouthAmericanSupremacyLocation.LIMA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.NAZCA_SEA, SouthAmericanSupremacyLocation.BAHIA_DE_ARICA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.PUNTA_ARENAS, SouthAmericanSupremacyLocation.ARAUNCANIAN);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.ARICA, SouthAmericanSupremacyLocation.AREQUIPA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.ARICA, SouthAmericanSupremacyLocation.ATACAMA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.ARICA, SouthAmericanSupremacyLocation.BAHIA_DE_ARICA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.BAHIA_SAO_MARCOS, SouthAmericanSupremacyLocation.BAHIA_DE_TODOS_OS_SANTOS);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.BAHIA_SAO_MARCOS, SouthAmericanSupremacyLocation.SALVADOR);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.BAHIA_SAO_MARCOS, SouthAmericanSupremacyLocation.ATLANTIC_OCEAN);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.BAHIA_SAO_MARCOS, SouthAmericanSupremacyLocation.MARANHAO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.RIO_GRANDE_DO_SUL, SouthAmericanSupremacyLocation.MONTEVIDEO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.RIO_GRANDE_DO_SUL, SouthAmericanSupremacyLocation.SAO_PAULO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.RIO_GRANDE_DO_SUL, SouthAmericanSupremacyLocation.PARANA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.RIO_GRANDE_DO_SUL, SouthAmericanSupremacyLocation.RIO_DE_LA_PLATA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.RIO_GRANDE_DO_SUL, SouthAmericanSupremacyLocation.MISIONES);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.PARA, SouthAmericanSupremacyLocation.MANAUS);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.PARA, SouthAmericanSupremacyLocation.MATO_GROSSO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.PARA, SouthAmericanSupremacyLocation.BOCA_DE_NAVIOS);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.PARA, SouthAmericanSupremacyLocation.MARANHAO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.ASUNCION, SouthAmericanSupremacyLocation.PARANA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.ASUNCION, SouthAmericanSupremacyLocation.CORRIENTES);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.ASUNCION, SouthAmericanSupremacyLocation.MISIONES);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.ASUNCION, SouthAmericanSupremacyLocation.CONCEPCION);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.COPIAGO, SouthAmericanSupremacyLocation.ANTOFAGASTA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.COPIAGO, SouthAmericanSupremacyLocation.VALPARAISO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.COPIAGO, SouthAmericanSupremacyLocation.GOLFO_DE_GUAFO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.PATAGONIA, SouthAmericanSupremacyLocation.BAHIA_BLANCA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.PATAGONIA, SouthAmericanSupremacyLocation.ARAUNCANIAN);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.PATAGONIA, SouthAmericanSupremacyLocation.GOLFO_DE_SAN_JORGE);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.GOLFO_DE_DARIEN, SouthAmericanSupremacyLocation.SANTA_MARTA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.GOLFO_DE_DARIEN, SouthAmericanSupremacyLocation.MARACAIBO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.GOLFO_DE_DARIEN, SouthAmericanSupremacyLocation.CARACAS);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.GOLFO_DE_DARIEN, SouthAmericanSupremacyLocation.GOLFO_DE_PARIA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.GOLFO_DE_DARIEN, SouthAmericanSupremacyLocation.CARTAGENA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.MEDELLIN, SouthAmericanSupremacyLocation.CARTAGENA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.MEDELLIN, SouthAmericanSupremacyLocation.CALI);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.MEDELLIN, SouthAmericanSupremacyLocation.GOLFO_DE_PANAMA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.SALVADOR, SouthAmericanSupremacyLocation.BAHIA_DE_TODOS_OS_SANTOS);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.SALVADOR, SouthAmericanSupremacyLocation.BAHIA_SAO_MARCOS);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.SALVADOR, SouthAmericanSupremacyLocation.RIO_DE_JANEIRO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.SANTIAGO, SouthAmericanSupremacyLocation.VALPARAISO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.SANTIAGO, SouthAmericanSupremacyLocation.ARAUNCANIAN);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.SANTIAGO, SouthAmericanSupremacyLocation.DRAKE_PASSAGE);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.SANTIAGO, SouthAmericanSupremacyLocation.GOLFO_DE_GUAFO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.AMAZONAS, SouthAmericanSupremacyLocation.MANAUS);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.AMAZONAS, SouthAmericanSupremacyLocation.MATO_GROSSO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.CALI, SouthAmericanSupremacyLocation.BAHIA_SECHURA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.CALI, SouthAmericanSupremacyLocation.QUITO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.CALI, SouthAmericanSupremacyLocation.MEDELLIN);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.CALI, SouthAmericanSupremacyLocation.GOLFO_DE_PANAMA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.GOLFO_DE_SAN_JORGE, SouthAmericanSupremacyLocation.SOUTH_ATLANTIC_OCEAN);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.GOLFO_DE_SAN_JORGE, SouthAmericanSupremacyLocation.BAHIA_BLANCA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.GOLFO_DE_SAN_JORGE, SouthAmericanSupremacyLocation.PATAGONIA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.GOLFO_DE_SAN_JORGE, SouthAmericanSupremacyLocation.RIO_DE_LA_PLATA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.GOLFO_DE_SAN_JORGE, SouthAmericanSupremacyLocation.ISLAS_MALVINAS);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.CORRIENTES, SouthAmericanSupremacyLocation.ASUNCION);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.CORRIENTES, SouthAmericanSupremacyLocation.MISIONES);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.GOLFO_DE_GUAFO, SouthAmericanSupremacyLocation.ANTOFAGASTA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.GOLFO_DE_GUAFO, SouthAmericanSupremacyLocation.VALPARAISO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.GOLFO_DE_GUAFO, SouthAmericanSupremacyLocation.ISLAS_JUAN_FERNANDEZ);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.GOLFO_DE_GUAFO, SouthAmericanSupremacyLocation.COPIAGO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.GOLFO_DE_GUAFO, SouthAmericanSupremacyLocation.SANTIAGO);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.GOLFO_DE_GUAFO, SouthAmericanSupremacyLocation.DRAKE_PASSAGE);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.GOLFO_DE_GUAFO, SouthAmericanSupremacyLocation.BAHIA_DE_ARICA);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.CONCEPCION, SouthAmericanSupremacyLocation.ASUNCION);
        addEdge(fleetGraph, SouthAmericanSupremacyLocation.CONCEPCION, SouthAmericanSupremacyLocation.PARANA);
    }

    public static MapVariant getInstance() {
        return INSTANCE;
    }

    private void addEdge(Map<Location, Set<Location>> graph, Location one, Location two) {
        graph.putIfAbsent(one, new HashSet<>());
        graph.putIfAbsent(two, new HashSet<>());
        graph.get(one).add(two);
        graph.get(two).add(one);
    }

    private void addEdge(Location one, Location two) {
        graph.putIfAbsent(one, new HashSet<>());
        graph.putIfAbsent(two, new HashSet<>());
        graph.get(one).add(two);
        graph.get(two).add(one);
    }

    @Override
    public SortedSet<Country> getCountries() {
        return new TreeSet<>(Set.of(
            Country.ARGENTINA,
            Country.BOLIVIA,
            Country.BRASIL,
            Country.CHILE,
            Country.COLOMBIA,
            Country.PARAGUAY,
            Country.PERU,
            Country.VENEZUELA
        ));
    }

    @Override
    public Map<Location, Set<Location>> getMovementGraph() {
        return graph;
    }

    @Override
    public Location parseLocation(String name) {
        return SouthAmericanSupremacyLocation.findByName(name);
    }

    @Override
    public Map<Location, Set<Location>> getMovementGraph(UnitType unitType) {
        if (unitType.equals(UnitType.FLEET)) {
            return fleetGraph;
        } else {
            return graph;
        }
    }

    @Override
    public long getStartingYear() {
        return 1835;
    }
}
